"""rename department

Revision ID: 1c8c79ab4c48
Revises: ce1e064a9f79
Create Date: 2024-10-18 00:17:29.400519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8c79ab4c48'
down_revision = 'ce1e064a9f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###