"""rename address

Revision ID: 83da391e8a5c
Revises: 1c8c79ab4c48
Create Date: 2024-10-18 00:19:16.354025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83da391e8a5c'
down_revision = '1c8c79ab4c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###